name: Kamin space
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6731
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2b29'
    - '#9d9996'
    - '#e3e2de'
    - '#41525b'
    - '#c4b8a8'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.019873675890266895
  rhythmicContrast: 0.2327822654042393
purpose: []
